In [5]:
# iterations
import numpy as np
#1d array
array_1d=np.array([1,2,3,4,5,6])
#iterate the elements in this array
print("Array_1d :",array_1d)
for elements in array_1d:
    print(elements)

Array_1d : [1 2 3 4 5 6]
1
2
3
4
5
6


In [7]:
array_2d= np.array([[1,2,3,],[4,5,6],[7,8,9]])
print("2d array is",array_2d)
#iterate 2d array
for elements in array_2d:
    print(elements)

2d array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


In [8]:
# how we can arrange into sepperate 
array_2d= np.array([[1,2,3,],[4,5,6],[7,8,9]])
print("2d array is",array_2d)
#iterate 2d array
for rows in array_2d:
    print(rows)
    for elements in rows:
        print(elements)
        
    

2d array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


In [10]:
array_2d= np.array([[1,2,3,],[4,5,6],[7,8,9]])
print("2d array is",array_2d)
for elements in np.nditer(array_2d):
    print (elements)

2d array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


In [15]:
#iterate the elements with index
array_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
for index , elements in np.ndenumerate(array_2d):
    print(f"Index: {index}, element: {elements}")

Index: (0, 0), element: 1
Index: (0, 1), element: 2
Index: (0, 2), element: 3
Index: (1, 0), element: 4
Index: (1, 1), element: 5
Index: (1, 2), element: 6
Index: (2, 0), element: 7
Index: (2, 1), element: 8
Index: (2, 2), element: 9
