In [1]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
concat_array=np.concatenate((array1,array2))
print("concat_array : ", concat_array)

concat_array :  [1 2 3 4 5 6]


In [2]:

#create a multidimenstional
array2d_1 = np.array([[1,2,3],[4,5,6]])
array2d_2 = np.array([[7,8,9],[10,11,12]])

#vertically and horizontally


In [8]:
#vertically
vstack_array = np.vstack((array2d_1,array2d_2))
print("vertically stacked array is:",vstack_array)


vertically stacked array is: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [10]:
#horizontally
array2d_1 = np.array([[1,2,3],[4,5,6]])
array2d_2 = np.array([[7,8,9],[10,11,12]])
hstack_array = np.hstack((array2d_1,array2d_2))
print("horizontaly:", hstack_array)


horizontaly: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
