In [4]:
1.      # Print the shape of a 2-D array
2.       #Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4
3.       # Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 4 arrays, each with 3 elements:
4.       # Convert the following 1-D array with 12 elements into a 3-D array. The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
5.       # Check if the returned array is a copy or a view


5.0

In [5]:
import numpy as np 

In [12]:
# Create a 2-D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
# Print the shape of the 2-D array
print("Shape of the array is:",array_2d.shape)

Shape of the array is: (2, 3)


In [13]:
# Create an array with 5 dimensions
array_5d = np.array([1, 2, 3, 4], ndmin=5)
# Print the array 
print("Array with 5 dimensions:\n", array_5d)
# Verify that the last dimension has value 4
print("Last dimension size:", array_5d.shape[-1])

Array with 5 dimensions:
 [[[[[1 2 3 4]]]]]
Last dimension size: 4


In [9]:
# Create a 1-D array with 12 elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# Reshape the array into a 2-D array with 4 arrays, each with 3 elements
array_2d = array_1d.reshape(4, 3)
# Print the reshaped array
print("Reshaped 2-D array:\n", array_2d)

Reshaped 2-D array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
# Create a 1-D array with 12 elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# Reshape the array into a 3-D array 
# each containing 3 arrays of 2 elements
array_3d = array_1d.reshape(2, 3, 2)
# Print the reshaped array
print("Reshaped 3-D array:\n", array_3d)

Reshaped 3-D array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
# Create a 1-D array with 12 elements
print("The orginal or 1D array is : ",array_1d)
array_view = array_1d.reshape(4, 3)
array_copy = array_1d.reshape(4, 3).copy()
print("Is the reshaped array a view? ", array_view.base is array_1d)
print("The view array is : ",array_view)
print("Is the reshaped array a copy? ", array_copy.base is array_1d)
print("The view array is : ",array_copy)

The orginal or 1D array is :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Is the reshaped array a view?  True
The view array is :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Is the reshaped array a copy?  False
The view array is :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
