In [1]:
import numpy as np

# Example array
arr = np.array([0, 1, 2, 0, 3, 0, 4])

# Count non-zero values
non_zero_count = np.count_nonzero(arr)
print(f"Number of non-zero values: {non_zero_count}")


Number of non-zero values: 4


In [2]:
# Empty array of shape (3, 3)
empty_array = np.empty((3, 3))
print("Empty Array:\n", empty_array)

# Full array of shape (3, 3) with all values as 7
full_array = np.full((3, 3), 7)
print("Full Array:\n", full_array)


Empty Array:
 [[2.22520627e-307 1.50199531e-307 5.11798224e-307]
 [3.44897992e-307 4.22795269e-307 9.34609790e-307]
 [6.23037657e-307 1.29061142e-306 6.23040373e-307]]
Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [3]:
# Example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Number of rows and columns
rows, cols = matrix.shape
print(f"Number of rows: {rows}, Number of columns: {cols}")


Number of rows: 3, Number of columns: 3


In [5]:
# Sum of all values in the matrix
matrix_sum = np.sum(matrix)
print(f"Sum of values in the matrix: {matrix_sum}")


Sum of values in the matrix: 45


In [4]:
# Example 3x3 matrix
matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Example 4x4 matrix
matrix_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Sum of diagonal elements
diagonal_sum_3x3 = np.trace(matrix_3x3)
diagonal_sum_4x4 = np.trace(matrix_4x4)

print(f"Sum of diagonal elements (3x3): {diagonal_sum_3x3}")
print(f"Sum of diagonal elements (4x4): {diagonal_sum_4x4}")


Sum of diagonal elements (3x3): 15
Sum of diagonal elements (4x4): 34


In [6]:
# Example matrix
matrix_to_inverse = np.array([[1, 2], [3, 4]])

# Inverse of the matrix
matrix_inverse = np.linalg.inv(matrix_to_inverse)
print("Inverse of the matrix:\n", matrix_inverse)


Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
# Example matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
product = matrix1 @ matrix2
# or
product = np.matmul(matrix1, matrix2)
print("Matrix Multiplication Result:\n", product)


Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [8]:
# Maximum and minimum values
max_value = np.max(matrix)
min_value = np.min(matrix)

print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")


Maximum value: 9
Minimum value: 1


In [9]:
# Example matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Addition
matrix_sum = matrix1 + matrix2
print("Matrix Addition Result:\n", matrix_sum)

# Subtraction
matrix_diff = matrix1 - matrix2
print("Matrix Subtraction Result:\n", matrix_diff)


Matrix Addition Result:
 [[ 6  8]
 [10 12]]
Matrix Subtraction Result:
 [[-4 -4]
 [-4 -4]]


In [10]:
# Example array
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Frequency of unique values
unique_values, counts = np.unique(array, return_counts=True)
frequency = dict(zip(unique_values, counts))
print("Frequency of unique values:\n", frequency)


Frequency of unique values:
 {1: 1, 2: 2, 3: 3, 4: 4}
